# The Monty Hall Problem

Let's start with a puzzle so famous it was used as the opening scene of the Kevin Spacey movie, *21*. The origin of its fame traces to a magazine columnist by the name of Marilyn vos Savant.


## Ask Marilyn

Marilyn vos Savant has the highest IQ ever recorded. At least, the *Guinness Book of Records* said so until they dropped this category in 1990 on the grounds that IQ tests weren't reliable enough. But we'll come back to IQ-bashing later. What I'm getting at is: she's famous for being smart.

In her column for *Parade* magazine, called "Ask Marilyn", she answers hard questions from readers: puzzles, brain teasers, philosophical quandaries... you name it. When she published her answer to our first puzzle, a bunch of people with fancy credentials wrote in to complain she was wrong. Here was the question:

> Suppose you’re on a game show, and you’re given the choice of three doors. Behind one door is a car, behind the others, goats. You pick a door, say #1, and the host, who knows what’s behind the doors, opens another door, say #3, which has a goat. He says to you, "Do you want to pick door #2?" Is it to your advantage to switch your choice of doors?
---*Craig F. Whitaker, Columbia, Maryland*

If you're like me, your gut says it doesn't matter. There are two doors left; one has the car behind it; so they both have the same one-in-two chance of being a winner. Flip a coin, stick or move. It doesn't matter.

But Marilyn says you should switch! And you know what? She's right.

Why? Because the host knows where the car is, and he's not going to just show it to you. That means he effectively just told you it's behind behind door #2, unless you got lucky with your first pick of door #1. Because unless you got lucky on your first pick, his choice of which door to open was forced. He had to open door #3 to avoid showing you the car behind door #2. Unless, again, you got lucky on your first pick. But that's only a one-in-three chance. So there's a two-in-three chance door #2 has the car.

Still don't believe me? It's okay, that's normal.

Here's how Marilyn convinced her readers to switch. Imagine the same game, but with 100 doors. You pick door #1, and the host opens every single other door except one, let's say #42. What do you think now, is it just a fifty-fifty shot? No way! Unless you got *very* lucky on your first pick and the car is behind door #1, you've just learned that the lucky door is #42.

*Still* don't believe me?? That's okay, that's normal too! One of the most famous mathematicians of the 20th century wasn't convinced either. Paul Erdős published over 1,500 papers in mathematics, more than any other mathematician ever. A lot of them were even advanced work in probability theory! But when his friend, Andrew Vázsonyi, told him about this puzzle, he wasn't having it. He kept asking Vázsonyi for a better explanation why he should switch. Vázsonyi even showed him a computer simulation he'd made of the game, where switching doors won the car two-thirds of the time. But Erdős still wanted a pure, mathematical explanation.

(Fun facts about Erdős by the way: he basically lived for math. He would travel the world, visiting friends at their houses, often uninvited. He would drink coffee (and, eventually, take methamphetamine) and do math with his host, until whatever problem they solved whatever problem the host had been working on before Erdős showed up. Then he'd move on to the next house, and the next problem. He was such a character, and so ubiquitous, that mathematicians make a game of tracing their connection to him. Every mathematician has an "Erdős number". It's kind of like six degrees of Kevin Bacon. Erdős (and only Erdős) has the number zero. People who coauthored papers with Erdős have number 1. People who coauthored with them have number 2. Their coauthors have number 3, and so on.)


## Three Prisoners

In my last year as an undergraduate I took a class that changed my life. It literally defined my career as a philosopher. To this day, my career is devoted to the concepts, tools, and problems I met there for the first time.

One of those problems, which my professor assigned as homework, goes like this:

> Three prisoners, A, B, and C, with apparently equally good records have applied for parole. The parole board has decided to release two of the three, and the prisoners know this but not which two. A warder friend of prisoner A knows who will be released. Prisoner A realizes that it would be unethical to ask the warder if he, A, is to be released, but thinks of asking for the name of one prisoner other than himself who is to be released. He thinks that before he asks, his chances of release are 2/3. He thinks that if the warder says "B will be released," his own chances have now gone down to 1/2, because either A and B or B and C are to be released. And so A decided not to reduce his chances by asking. However, A is mistaken in this calculations. Explain.

This homework problem got me so turned inside out, I ended up writing a computer program to run simulations of it! Just like Vázsonyi. (Fools and wise men think alike, I guess.)

Well, my professor laughed. He called my computer simulation an "empirical" approach, and he didn't mean it as a compliment. Like Erdős, he wanted me to use *reason*, not a brute-force, computerized experiment.

Well, here's one reasoned argument that prisoner A is mistaken. By A's logic, their chances would also go down to 1/2 if the warder identified C instead of B. Because then there would be only one more prisoner to be released, with two candidates remaining: A and B. But if A's chances would be the same no matter what the warder said, then the warder's response couldn't possibly be informative. If your chances of having a certain disease are the same whether a certain medical test comes up positive or not, then the test must be useless, right?

This argument is right as far as it goes. But it doesn't really explain where the prisoner went wrong. It just tells us she must've gone wrong *somewhere*. But where?

I think the correct explanation involves a famous precept known as *The Principle of Total Evidence*. It says pretty much what it sounds like: to get the true probability of something, you have to take account of *all* the evidence you have. And the warder wouldn't just be telling her that B will be released. She would also be telling her, implicitly, that the warder chose to identify B as one of the released prisoners.

It's really counterintuitive that this extra information makes a difference. But it turns out to make all the difference in the world. Here's one way to see how.

A knows B can't be the pardoned prisoner, because the warder said so. So there are two possibilities remaining:

  - A is the pardoned prisoner.
  - C is the pardoned prisoner.

In the first scenario, where A has been pardoned, the guard had a choice between identifying B or C in her response. She chose to identify B, but she could have identified C instead. But in the second scenario, the guard had no choice. She had to name B, since she couldn't tell A that she's still condemned.

So when the guard says "B is still condemned", her report is exactly what you'd expect in the second scenario, where C was pardoned. Whereas in the first scenario, where A was pardoned, the guard's report was half as likely. She could just as easily have named C instead. So the guard's report fits twice as well with the second scenario. And that's why A's chance of survival is still 1/3.

It helps to visualize the idea. Start with the king's decision about who to pardon. He chooses one of the three prisoners at random, so each has the same 1/3 chance:
![Tree Diagram]
Then consider the guard's options. If A is pardoned, she can choose to name either B or C. But if B is pardoned, she has to name C---otherwise she'll give away A's fate. And likewise, she has to name C if B is pardoned. So there are two possible outcomes where the guard names B:
![Tree Diagram 2]
And look! One of them is half as likely as the other, namely the one where A was pardoned. So when the guard names B, A's chance of having been pardoned is half that of still being condemned. In other words, her chance of survival is 1/3, versus a 2/3 chance of still being condemned.

So A's chances really do stay fixed. The warden's report is no reprieve. It makes no difference to A's chances, as seems right.


## Monty Hall Again

Erdős left Vázsonyi's house unsatisfied and unconvinced. But a few days later he called: someone had finally explained to his satisfaction why you should switch doors in the Monty Hall problem. "He proceeded to tell me the reasoning", said Vázsonyi, "but I couldn't fathom his explanation."

I guess we'll never know what persuaded Erdős. But luckily we don't need to, because the same technique we used on the three-prisoner puzzle works on Monty Hall.

We can even use the same tree diagram, we just have to change the labels. The first branching-point now corresponds to the placement of the prize, where each door has the same 1/3 probability:
![Tree Diagram 3]
The second tier of branches represents Monty's decision about which door to open. And same as the guard, his hand is forced in all but one case. Recall: your initial choice was door A. So if the prize is behind door B, Monty has to open door C. Otherwise he'll be showing you that you have the wrong door. Likewise, he has to open B if the prize is behind C. Only if the prize is behind A does Monty have a choice. So there are two possible situations where Monty opens door B:
![Tree Diagram 4]
But one of them is half as likely as the other, namely the one where the prize is behind door A. So the prize is more likely behind door C. Switch!

The Principle of Total Evidence is clearly something to take seriously. To get the right answer, you have to take account of all the information you have. Monty isn't just showing you that door B is a bust, he's also telling you he's  chosen to give you that information.

Here's another way of think about this lesson. It's as important to consider *how* you get your information as it is to consider what information you got. These days there's a lot of talk about the dangers filter bubbles. But the news has always been a selective window onto the world, because only some things sell. "Man Bites Dog" is news, as journalists say, but "Dog Bites Man" is not. To take a more political and more realistic example from the recent news: "Seven Die in Terrorist Attack on London Bridge" is news while "Thousands Die Quietly of Cancer" is not.
