# A Missing Ingredient?

Our last decision puzzle is the simplest in a way, but also perhaps the most troubling. It sets probability to the side, focusing instead on questions of value.


## The Self-Torturer

Suppose you volunteer for an experiment at the psychology lab:

> A small, portable device runs an electric current through your body. The device has a dial with a thousand settings. The lowest setting is so weak you can't even feel it, while setting 1,000 is excruciating---almost enough to make you black out.
>
> But the difference between adjacent settings is so mild you can't tell the difference. Not between settings 1 and 2, nor between 500 and 501, nor between 999 and 1,000.
>
> Each day, the experimenters will offer you $10,000 to turn the dial up one notch. And there is no turning back: once you accept the day's offer, you must live with the pain for the rest of your life.
>
> What setting will you stop at?

Maybe you're thinking this is easy. A few hundred grand is worth some mild, lifelong discomfort. But no amount of money is worth living in debilitating pain for the rest of your days. So you'll go up to some low setting, say 20, and then stop. You'll be $200,000 richer, and the pain will be tolerable.

But here's the catch: why not go up to 21 instead? You can't tell the difference between 20 and 21. And another $10,000 would have its uses. So aren't you leaving money on the table?

No matter what setting you stop at, the same question will arise. You could always have upped the dial by one and walked away ten grand richer with no noticeable difference in pain.

Apparently, no matter what level you stop at, it's irrational. You'll always be leaving ten grand on the table. You'll always be walking away from "free" money.

Unless of course you go all the way up to setting 1,000. But then you'll live the rest of your life in so much pain you won't even be able to enjoy your winnings.


## The Ice Cream Conundrum

The self-torturer's dilemma seems far fetched and fantastical, but we actually face such dilemmas every day.

When there's a tub of ice cream in the freezer, you have to stop eating from it at some point. Some bite must be your last of the day. Yet no single bite makes the difference between being as healthy as you'd like and not.

If you take 50 bites, why did you stop there? You could have enjoyed just one more bite without any noticeable difference to your health. So aren't you denying yourself pleasure unnecessarily, and isn't that irrational?


## The Moral

Up to now we've focused on tradeoffs between risks and rewards. But there's no element of chance in these puzzles, no risks at play. You know the consequences of eating ice cream. And we could allow you to try out various settings on the self-torture device before starting the experiment.

These puzzles focus our attention on the reward side of the equation. The problem is how to weigh competing goods, like money vs. bodily comfort, or gustatory pleasure vs. health. At what point should you decline an increase in one good in exchange for the other?

Decision theory doesn't say. In the theory of expected utility, we leave this problem to the decision maker. We just assume that she has a utility function, which we then use to advise her on the other sort of tradeoff: risks vs. rewards, probabilities multiplied by utilities.

In a way then, the puzzle of the self-torturer is a counterpoint to Bertrand's paradox. Just as the laws of probability don't tell us what probabilities to plug into the expected utility formula, the theory of utility doesn't tell us the relevant utilities.

According to one popular school of thought, leaving these questions unanswered is the right thing to do. They do not have objective answers, say many decision theorists. People differ in their tastes, and in their beliefs. So it is only fitting that we leave it to them to decide the values of the $Pr$ and $U$ functions themselves.

But I have my doubts. It may be hard to say what the correct probabilities are, or which bit of ice cream should be your last. But hard questions can still have answers. They can even have answers when we have no hope of ever knowing what those are.
